import { useState } from 'react';
import { Eye, Heart, LogOut, MapPin, Save, X } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useAuthStore } from '../store/authStore';
import { useOrderStore } from '../store/orderStore';
import { useWishlistStore } from '../store/wishlistStore';
import ProductCard from '../components/common/ProductCard';

export default function ProfilePage() {
  const navigate = useNavigate();
  const { user, updateProfile, logout } = useAuthStore();
  const orders = useOrderStore((state) => state.orders);
  const wishlist = useWishlistStore((state) => state.items);
  const [activeTab, setActiveTab] = useState('orders');
  const [selectedOrder, setSelectedOrder] = useState(null);
  const [addresses, setAddresses] = useState(user?.address ? [user.address] : []);
  const [newAddress, setNewAddress] = useState('');
  const [form, setForm] = useState({ name: user?.name || '', phone: user?.phone || '', address: user?.address || '' });
  const handleSubmit = (event) => { event.preventDefault(); updateProfile(form); toast.success('Profile updated'); };
  const handleLogout = () => { logout(); navigate('/'); };
  const addAddress = (event) => { event.preventDefault(); if (!newAddress.trim()) return; setAddresses((current) => [...current, newAddress.trim()]); setNewAddress(''); toast.success('Address saved'); };

  return (
    <main className="max-w-6xl mx-auto w-full px-6 py-10 bg-gray-50">
        <div className="flex items-center justify-between mb-8"><div><p className="text-sm text-rose-500 font-semibold">Account</p><h1 className="text-3xl font-bold text-gray-900 mt-1">Welcome, {user?.name}</h1></div><button onClick={handleLogout} className="flex items-center gap-2 text-sm text-gray-500 hover:text-rose-600"><LogOut size={16} /> Sign out</button></div>
        <div className="bg-white border border-gray-100 rounded-xl overflow-hidden"><div className="flex overflow-x-auto border-b border-gray-100">{[['orders', 'Order history'], ['addresses', 'Saved addresses'], ['wishlist', 'Wishlist']].map(([value, label]) => <button key={value} onClick={() => setActiveTab(value)} className={`px-5 py-4 text-sm font-semibold whitespace-nowrap border-b-2 transition ${activeTab === value ? 'text-rose-600 border-rose-500' : 'text-gray-500 border-transparent hover:text-gray-800'}`}>{label}</button>)}</div><div className="p-6">
          {activeTab === 'orders' && <div><div className="flex items-center justify-between mb-5"><h2 className="font-semibold text-gray-900">Your orders</h2><span className="text-xs text-gray-400">{orders.length} total</span></div>{orders.length === 0 ? <p className="text-sm text-gray-500">Your orders will appear here.</p> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr className="text-xs uppercase tracking-wide text-gray-400 border-b border-gray-100"><th className="pb-3">Order</th><th className="pb-3">Items</th><th className="pb-3">Date</th><th className="pb-3">Total</th><th className="pb-3">Status</th><th className="pb-3" /></tr></thead><tbody>{orders.map((order) => <tr key={order.id} className="border-b border-gray-50 last:border-0"><td className="py-4 font-semibold text-gray-900">{order.id}</td><td className="py-4 text-gray-500">{order.items?.reduce((sum, item) => sum + item.quantity, 0)} item(s)</td><td className="py-4 text-gray-500">{order.date}</td><td className="py-4 font-semibold">${Number(order.total).toFixed(2)}</td><td className="py-4"><span className={`text-xs font-semibold px-2.5 py-1 rounded-full ${order.status === 'Delivered' ? 'bg-emerald-50 text-emerald-600' : order.status === 'Shipped' ? 'bg-blue-50 text-blue-600' : 'bg-amber-50 text-amber-600'}`}>{order.status}</span></td><td className="py-4 text-right"><button onClick={() => setSelectedOrder(order)} className="text-rose-600 hover:text-rose-700" title="View receipt"><Eye size={17} /></button></td></tr>)}</tbody></table></div>}</div>}
          {activeTab === 'addresses' && <div className="max-w-xl"><h2 className="font-semibold text-gray-900 mb-5">Saved addresses</h2><div className="space-y-3 mb-6">{addresses.map((address, index) => <div key={`${address}-${index}`} className="flex items-start gap-3 border border-gray-100 rounded-lg p-4"><MapPin size={17} className="text-rose-500 mt-0.5" /><p className="text-sm text-gray-600">{address}</p></div>)}</div><form onSubmit={addAddress} className="space-y-3"><textarea value={newAddress} onChange={(event) => setNewAddress(event.target.value)} placeholder="Add another delivery address" className="w-full border border-gray-200 rounded-lg px-3 py-2 text-sm min-h-20 outline-none focus:border-rose-400" /><button className="flex items-center gap-2 bg-gray-900 hover:bg-rose-600 text-white font-semibold rounded-lg px-4 py-2.5 transition"><MapPin size={16} /> Save address</button></form></div>}
          {activeTab === 'wishlist' && <div><div className="flex items-center gap-2 mb-5"><Heart size={18} className="text-rose-500" fill="currentColor" /><h2 className="font-semibold text-gray-900">Saved for later</h2></div>{wishlist.length ? <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-5">{wishlist.map((product) => <ProductCard key={product.id} product={product} />)}</div> : <p className="text-sm text-gray-500">Your wishlist is empty.</p>}</div>}
        </div></div>
        <form onSubmit={handleSubmit} className="mt-8 bg-white border border-gray-100 rounded-xl p-6 space-y-5"><h2 className="font-semibold text-gray-900">Personal details</h2><div className="grid md:grid-cols-2 gap-5">{[['name', 'Full name'], ['phone', 'Phone']].map(([key, label]) => <label key={key} className="block text-sm font-medium text-gray-600">{label}<input value={form[key]} onChange={(event) => setForm({ ...form, [key]: event.target.value })} className="mt-2 w-full border border-gray-200 rounded-lg px-3 py-2 outline-none focus:border-rose-400" /></label>)}</div><label className="block text-sm font-medium text-gray-600">Default address<textarea value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} className="mt-2 w-full border border-gray-200 rounded-lg px-3 py-2 min-h-20 outline-none focus:border-rose-400" /></label><p className="text-sm text-gray-400">{user?.email}</p><button className="flex items-center gap-2 bg-gray-900 hover:bg-rose-600 text-white font-semibold rounded-lg px-4 py-2.5 transition"><Save size={16} /> Save changes</button></form>
      {selectedOrder && <div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/40" onClick={() => setSelectedOrder(null)} /><div className="relative bg-white rounded-xl shadow-xl w-full max-w-lg p-6"><button onClick={() => setSelectedOrder(null)} className="absolute top-4 right-4 text-gray-400"><X size={18} /></button><div id="receipt" className="space-y-5"><div><p className="text-xs uppercase tracking-wide text-rose-500 font-semibold">ToyAlfa invoice</p><h2 className="text-xl font-bold text-gray-900 mt-1">{selectedOrder.id}</h2><p className="text-sm text-gray-500 mt-1">Placed on {selectedOrder.date}</p></div><div className="border-y border-gray-100 py-4 space-y-3">{selectedOrder.items.map((item) => <div key={item.id} className="flex justify-between text-sm"><span className="text-gray-600">{item.name} x {item.quantity}</span><span className="font-semibold">${(item.price * item.quantity).toFixed(2)}</span></div>)}</div><div className="flex justify-between font-bold text-gray-900"><span>Total</span><span>${Number(selectedOrder.total).toFixed(2)}</span></div><p className="text-sm text-gray-500">Delivery: {selectedOrder.address}</p></div><button onClick={() => window.print()} className="mt-5 w-full bg-rose-500 hover:bg-rose-600 text-white font-semibold rounded-lg py-2.5">Print receipt</button></div></div>}
    </main>
  );
}